extensions:
    silk-menu-custom:
        module: pim/menu/item
        parent: pim-menu-activity-navigation-block
        position: 500
        config:
            title: page_title.silk_custom_index_title
            to: silk_custom_index
