# silk_custom:
#     resource: '@SilkUIBundle/Resources/config/routing/silk_custom.yml'
#     prefix: /custom
#     defaults: { _controller: FrameworkBundle:Template:template, template: SilkUIBundle:Custom:index.html.twig }

silk_custom_index:
    path: /custom/

